name: Push

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: RunLint
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: echo LINT

  test:
    needs: [lint]
    runs-on: windows-latest
    steps:
      - name: Setup VSTest.exe
        uses: Malcolmnixon/Setup-VSTest@v4

      - name: Create Release Directory
        run: mkdir -p x64\Release

      - name: Print Root Directory Contents
        run: dir ${{ env.GITHUB_WORKSPACE }}

      - name: Print soft_arch_assignment Contents
        run: dir ${{ env.GITHUB_WORKSPACE }}\soft_arch_assignment

      - name: RunTests
        working-directory: ${{env.GITHUB_WORKSPACE}}\soft_arch_assignment
        run: VSTest.Console.exe UnitTest1.dll

      - name: UploadBinaries
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: x64\Release
          if-no-files-found: error
