name: Push

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: RunLint
      run: echo LINT

  test:
    needs: [lint]
    runs-on: windows-latest

    steps:
    - name: Setup VSTest.exe
      uses: Malcolmnixon/Setup-VSTest@v4

    - name: DownloadBinaries
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: x64\Release

    - name: RunTests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: VSTest.Console.exe x64\Release\UnitTest1.dll

    - name: UploadBinaries
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: x64\Release

  SaveBinary:
    needs: [test]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: DownloadBinaries
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: x64\Release

    - name: stage
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: copy x64\Release\PipeplinesExe.exe .

    - name: addEmail
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git config --global user.email "olekaspt@mail.uc.edu"

    - name: addName
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git config --global user.name "Patrick Olelas"

    - name: add
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git add PipeplinesExe.exe

    - name: commit
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git commit -m "generated"

    - name: push
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git push

