name: Push

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: RunLint
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: echo LINT

  test:
    needs: [lint]
    runs-on: windows-latest
    steps:
      - name: Setup VSTest.exe
        uses: Malcolmnixon/Setup-VSTest@v4

      - name: Print Available Drives
        run: wmic logicaldisk get caption

      - name: Print Drive Contents
        run: |
          $drives = wmic logicaldisk get caption | Select-String -Pattern "[A-Z]:"
          foreach ($drive in $drives) {
            $driveLetter = $drive -replace "[^A-Z]", ""
            Write-Output "Contents of drive $driveLetter:"
            dir "$driveLetter:\" /s
          }

      - name: RunTests
        working-directory: soft_arch_assignment
        run: VSTest.Console.exe UnitTest1.dll

      - name: UploadBinaries
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: x64\Release
          if-no-files-found: error
