name: Push

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: RunLint
      run: echo LINT

  test:
    needs: [lint]
    runs-on: windows-latest

    steps:
    - name: Setup VSTest.exe
      uses: Malcolmnixon/Setup-VSTest@v4

    - name: DownloadBinaries
      uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: RunTests
      run: VSTest.Console.exe x64\Release\UnitTest1.dll

    - name: UploadBinaries
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: x64\Release\ # or path/to/artifact
      if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to 'warn'

