name: Push

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: RunLint
        run: echo "LINT"

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Print Available Drives
        run: lsblk -o NAME,MOUNTPOINT | grep -E '^[a-z]' | awk '{print $2}'

      - name: Print Drive Contents
        run: |
          mountpoints=$(lsblk -o NAME,MOUNTPOINT | grep -E '^[a-z]' | awk '{print $2}')
          for mountpoint in $mountpoints; do
            echo "Contents of mount point $mountpoint:"
            ls -l "$mountpoint"
          done

      - name: Print soft_arch_assignment Contents
        run: ls -l $GITHUB_WORKSPACE/soft_arch_assignment

      - name: Run Tests
        run: |
          # Replace this with your actual test commands
          echo "Running tests..."
          # Example: npm test, pytest, etc.

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: path/to/your/test/results
