name: Push

on:
  push:
    branches: [main]

jobs:
  test:
    needs: [build, lint]
    runs-on: windows-latest

    steps:
    - name: Setup VSTest.exe
      uses: Malcolmnixon/Setup-VSTest@v4

    - name: RunTests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: VSTest.Console.exe x64\Release\UnitTest1.dll

